name: Clean Chrome Extension ZIP (Only Install Files)

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # برای ایجاد Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # --- دیباگ: چک کن dist/ چی داره ---
      - name: Debug:List dist contents
        run: |
          echo "=== Contents of dist/ ==="
          ls -la dist/ || echo "dist/ folder not found or empty!"
          echo "=== All files in repo ==="
          ls -la

      # --- ساخت پوشه موقت برای فایل‌های نهایی ---
      - name: Prepare clean extension folder
        run: |
          mkdir -p extension-clean
          
          # کپی فقط فایل‌های ضروری (حتی اگر build نشد)
          cp manifest.json extension-clean/ || echo "manifest.json not found"
          cp -r public/* extension-clean/ 2>/dev/null || echo "public/ folder issue"
          
          # اگر dist/ وجود داشت، محتوای اون رو هم کپی کن (bundle.js و غیره)
          if [ -d "dist" ]; then
            cp -r dist/* extension-clean/ 2>/dev/null || echo "dist/ copy failed"
          fi

          # حذف فایل‌های غیرضروری از پوشه نهایی
          rm -rf extension-clean/src extension-clean/node_modules extension-clean/.github \
                 extension-clean/README.md extension-clean/LICENSE extension-clean/.gitignore \
                 extension-clean/package.json extension-clean/tsconfig.json \
                 extension-clean/webpack.config.js extension-clean/tailwind.config.js

          echo "=== Final clean folder ==="
          ls -la extension-clean/

      # --- ساخت ZIP فقط از پوشه تمیز ---
      - name: Create Clean ZIP
        run: |
          cd extension-clean
          zip -r ../proxy-configurator-v${{ github.ref_name }}.zip ./*
          cd ..
          echo "=== ZIP Contents ==="
          unzip -l proxy-configurator-v${{ github.ref_name }}.zip

      # --- آپلود ZIP به عنوان artifact (برای دیباگ) ---
      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-zip
          path: proxy-configurator-v${{ github.ref_name }}.zip

      # --- ایجاد Release بدون ZIP خودکار ---
      - name: Create Release (No Auto Source Code)
        uses: softprops/action-gh-release@v2
        with:
          files: proxy-configurator-v${{ github.ref_name }}.zip
          tag_name: ${{ github.ref_name }}
          name: "Version ${{ github.ref_name }} - Install ZIP"
          body: |
            **فقط فایل‌های نصب افزونه در این ZIP هست!**

            شامل:
            - `manifest.json`
            - `background.js`
            - `index.html`
            - `bundle.js`
            - `icons/`

            **نصب:**
            1. دانلود کن
            2. unzip کن
            3. `chrome://extensions/` → Developer Mode → Load unpacked → پوشه

            **بدون**: src/, README, LICENSE, node_modules, .github
          generate_release_notes: false
          draft: false
          prerelease: false
          # مهم: غیرفعال کردن ZIP خودکار
          append_body: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
