name: Create Clean ZIP Release for Chrome Extension (Debug & Strict)

on:
  push:
    tags:
      - 'v*'  # فقط برای تگ‌ها مثل v2.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build  # ساخت dist/ با فایل‌های نهایی

      - name: Debug - List dist contents
        run: |
          echo "=== Dist folder contents after build ==="
          ls -la dist/ || echo "Dist folder is empty or build failed!"
          echo "=== Full repo structure ==="
          ls -la .  # برای دیباگ کل repo

      - name: Create ZIP of dist folder contents only (strict exclusions)
        run: |
          # ورود به dist و ZIP فقط فایل‌های داخل (بدون پوشه dist/)
          if [ -d "dist" ] && [ "$(ls -A dist)" ]; then
            cd dist
            zip -r ../proxy-configurator-extension-v${{ github.ref_name }}.zip . -x "node_modules/*" "src/*" "*.log" ".git/*" "README*" "LICENSE*" ".gitignore" ".github/*" "package*" "tsconfig*" "webpack*" "tailwind*"  # exclusions کامل
            cd ..
          else
            echo "Dist empty - fallback ZIP of essential files"
            zip -r proxy-configurator-extension-v${{ github.ref_name }}.zip manifest.json public/ -x "public/src/*" "public/node_modules/*" "*.log" ".git/*"  # fallback به فایل‌های اصلی
          fi
          # لاگ محتوای ZIP برای چک
          echo "=== ZIP contents ==="
          unzip -l proxy-configurator-extension-v${{ github.ref_name }}.zip

      - name: Create Release and Attach ZIP
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: proxy-configurator-extension-v${{ github.ref_name }}.zip
          tag_name: ${{ github.ref }}
          name: 'Version ${{ github.ref_name }} - Clean Install ZIP (Debugged)'
          body: |
            ### تغییرات نسخه ${{ github.ref_name }}
            - ZIP فقط شامل فایل‌های ضروری: `manifest.json`, `background.js`, `bundle.js`, `index.html`, `icons/` (بدون src/, README, LICENSE, node_modules یا .github).
            - **نصب**: دانلود کن، unzip کن (فایل‌ها در root هستن)، `chrome://extensions/` > Developer Mode > **Load unpacked** > پوشه unzip‌شده.

            **لاگ Actions**: چک کن محتوای ZIP در Actions تب باشه. اگر مشکلی بود، issue باز کن.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
