name: Create ZIP Release for Chrome Extension (Only Install Files)

on:
  push:
    tags:
      - 'v*'  # اجرا فقط وقتی تگ مثل v2.0.0 push می‌کنی

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # چک‌اوت repo

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # نسخه Node

      - name: Install dependencies
        run: npm ci  # نصب سریع وابستگی‌ها

      - name: Build project
        run: npm run build  # اجرای build - پوشه dist/ رو می‌سازه با فایل‌های نهایی (manifest, bundle.js, icons, etc.)

      - name: Create ZIP of only dist folder contents
        run: |
          # ساخت ZIP فقط از محتوای dist/ (بدون src/, README, LICENSE و غیره)
          cd dist
          zip -r ../proxy-configurator-extension-v${{ github.ref_name }}.zip .  # ZIP همه فایل‌های داخل dist/ به root ZIP
          cd ..

      - name: Create Release and Attach ZIP
        uses: softprops/action-gh-release@v2  # ایجاد Release و attach ZIP
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: proxy-configurator-extension-v${{ github.ref_name }}.zip  # attach ZIP (نام با نسخه)
          tag_name: ${{ github.ref }}
          name: 'Version ${{ github.ref_name }} - Proxy Configurator Extension (Install ZIP)'
          body: |
            ### تغییرات نسخه ${{ github.ref_name }}
            - بیلد خودکار فایل‌های افزونه (فقط فایل‌های لازم برای نصب)
            - ZIP شامل: manifest.json, background.js, bundle.js, index.html, icons (بدون فایل‌های توسعه مثل src/ یا node_modules)
            - **نصب آسان**: دانلود کن، unzip کن، به `chrome://extensions/` برو، Developer Mode فعال کن، **Load unpacked** بزن و پوشه unzip‌شده رو انتخاب کن.

            **نکته امنیتی**: فقط از پراکسی‌های معتبر استفاده کن. برای تست، host: `proxy.example.com` و port: `1080` امتحان کن.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # توکن خودکار GitHub
